version: "3.3"

services:
  mappingsite:
    image: mappingsite
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 8080:8080
      - 443:8080

    volumes:
      - ../uploads/:/root/uploads

  postgres:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:${PGDATA}
    ports:
      - "5432:5432"

volumes:
  db-data:
